// Realistic SOC seed data. Nothing here is real.

export const analysts = [
  { name: "Elena Rossi", initials: "ER", role: "Tier 2 Analyst" },
  { name: "Marcus Chen", initials: "MC", role: "Threat Hunter" },
  { name: "Priya Nair", initials: "PN", role: "Incident Responder" },
  { name: "Jonas Weber", initials: "JW", role: "SOC Manager" },
  { name: "Amelia Ward", initials: "AW", role: "Tier 1 Analyst" },
  { name: "Yusuf Demir", initials: "YD", role: "Tier 3 Analyst" },
];

export const alerts = [
  {
    id: "ALT-24817",
    name: "Impossible travel activity detected",
    severity: "high" as const,
    status: "in-progress" as const,
    analyst: "Elena Rossi",
    rule: "IdentityProtection.ImpossibleTravel",
    mitre: "T1078 — Valid Accounts",
    ts: "2m ago",
    source: "Entra ID",
    user: "kate.morgan@contoso.com",
    device: "LT-KMORGAN-01",
  },
  {
    id: "ALT-24816",
    name: "Suspicious PowerShell encoded command",
    severity: "critical" as const,
    status: "new" as const,
    analyst: "—",
    rule: "EDR.Behavior.Powershell.EncodedCmd",
    mitre: "T1059.001 — PowerShell",
    ts: "6m ago",
    source: "Endpoint EDR",
    user: "svc-backup",
    device: "SRV-DB-07",
  },
  {
    id: "ALT-24815",
    name: "Password spray against tenant",
    severity: "high" as const,
    status: "escalated" as const,
    analyst: "Marcus Chen",
    rule: "IdentityProtection.PasswordSpray",
    mitre: "T1110.003 — Password Spraying",
    ts: "14m ago",
    source: "Entra ID",
    user: "multiple",
    device: "—",
  },
  {
    id: "ALT-24814",
    name: "Malicious attachment quarantined",
    severity: "medium" as const,
    status: "resolved" as const,
    analyst: "Amelia Ward",
    rule: "Email.Attachment.Malware",
    mitre: "T1566.001 — Spearphishing Attachment",
    ts: "38m ago",
    source: "Email Gateway",
    user: "invoice-inbox@contoso.com",
    device: "—",
  },
  {
    id: "ALT-24813",
    name: "Lateral movement via SMB admin share",
    severity: "critical" as const,
    status: "in-progress" as const,
    analyst: "Priya Nair",
    rule: "Network.LateralMovement.AdminShare",
    mitre: "T1021.002 — SMB/Windows Admin Shares",
    ts: "1h ago",
    source: "Endpoint EDR",
    user: "d.holt",
    device: "FIN-DESK-22",
  },
  {
    id: "ALT-24812",
    name: "Legacy authentication protocol used",
    severity: "low" as const,
    status: "closed" as const,
    analyst: "Amelia Ward",
    rule: "IdentityProtection.LegacyAuth",
    mitre: "T1078.004 — Cloud Accounts",
    ts: "2h ago",
    source: "Entra ID",
    user: "reports.svc",
    device: "—",
  },
  {
    id: "ALT-24811",
    name: "USB mass storage inserted (executive)",
    severity: "medium" as const,
    status: "open" as const,
    analyst: "Yusuf Demir",
    rule: "Endpoint.Device.USBInserted",
    mitre: "T1091 — Replication Through Removable Media",
    ts: "3h ago",
    source: "Endpoint EDR",
    user: "james.walker",
    device: "LT-EXEC-JWALKER",
  },
  {
    id: "ALT-24810",
    name: "Suspicious OAuth consent grant",
    severity: "high" as const,
    status: "new" as const,
    analyst: "—",
    rule: "M365.OAuth.SuspiciousConsent",
    mitre: "T1528 — Steal Application Access Token",
    ts: "3h ago",
    source: "M365 Defender",
    user: "sarah.chen@contoso.com",
    device: "—",
  },
];

export const incidents = [
  {
    id: "INC-4821",
    title: "Business email compromise — Finance department",
    severity: "critical" as const,
    status: "in-progress" as const,
    entities: 14,
    alerts: 7,
    owner: "Priya Nair",
    updated: "5m ago",
  },
  {
    id: "INC-4820",
    title: "Ransomware precursor on FIN-DESK-22",
    severity: "critical" as const,
    status: "escalated" as const,
    entities: 22,
    alerts: 11,
    owner: "Jonas Weber",
    updated: "18m ago",
  },
  {
    id: "INC-4819",
    title: "Credential access — password spray campaign",
    severity: "high" as const,
    status: "in-progress" as const,
    entities: 41,
    alerts: 6,
    owner: "Marcus Chen",
    updated: "1h ago",
  },
  {
    id: "INC-4818",
    title: "Data exfiltration attempt via SharePoint API",
    severity: "high" as const,
    status: "open" as const,
    entities: 9,
    alerts: 4,
    owner: "Elena Rossi",
    updated: "3h ago",
  },
  {
    id: "INC-4817",
    title: "Phishing kit — Adobe consent lure",
    severity: "medium" as const,
    status: "resolved" as const,
    entities: 18,
    alerts: 5,
    owner: "Amelia Ward",
    updated: "yesterday",
  },
];

export const identities = [
  {
    upn: "kate.morgan@contoso.com",
    name: "Kate Morgan",
    dept: "Legal",
    role: "General Counsel",
    risk: 82,
    mfa: "Enforced",
    lastSignin: "2m ago",
    location: "Zürich, CH → Lagos, NG",
    flags: ["Impossible travel", "Risky sign-in"],
  },
  {
    upn: "james.walker@contoso.com",
    name: "James Walker",
    dept: "Executive",
    role: "CFO",
    risk: 61,
    mfa: "Enforced",
    lastSignin: "12m ago",
    location: "New York, US",
    flags: ["USB inserted"],
  },
  {
    upn: "sarah.chen@contoso.com",
    name: "Sarah Chen",
    dept: "Product",
    role: "VP Product",
    risk: 47,
    mfa: "Enforced",
    lastSignin: "1h ago",
    location: "London, UK",
    flags: ["OAuth consent"],
  },
  {
    upn: "michael.johnson@contoso.com",
    name: "Michael Johnson",
    dept: "Engineering",
    role: "Staff Engineer",
    risk: 22,
    mfa: "Enforced",
    lastSignin: "3h ago",
    location: "Toronto, CA",
    flags: [],
  },
  {
    upn: "emily.davis@contoso.com",
    name: "Emily Davis",
    dept: "Marketing",
    role: "Growth Lead",
    risk: 14,
    mfa: "Enforced",
    lastSignin: "5h ago",
    location: "Berlin, DE",
    flags: [],
  },
  {
    upn: "svc-backup@contoso.com",
    name: "svc-backup",
    dept: "Infrastructure",
    role: "Service account",
    risk: 93,
    mfa: "Exempt",
    lastSignin: "6m ago",
    location: "Frankfurt, DE",
    flags: ["Encoded PowerShell", "Suspicious parent proc"],
  },
];

export const endpoints = [
  {
    host: "SRV-DB-07",
    os: "Windows Server 2022",
    owner: "svc-backup",
    risk: 91,
    status: "At risk",
    isolated: false,
    lastSeen: "just now",
    ip: "10.14.22.87",
  },
  {
    host: "FIN-DESK-22",
    os: "Windows 11 Pro 23H2",
    owner: "d.holt",
    risk: 88,
    status: "Isolated",
    isolated: true,
    lastSeen: "2m ago",
    ip: "10.22.7.51",
  },
  {
    host: "LT-KMORGAN-01",
    os: "macOS 14.5",
    owner: "kate.morgan",
    risk: 74,
    status: "At risk",
    isolated: false,
    lastSeen: "4m ago",
    ip: "10.7.19.104",
  },
  {
    host: "LT-EXEC-JWALKER",
    os: "Windows 11 Pro 23H2",
    owner: "james.walker",
    risk: 38,
    status: "Investigating",
    isolated: false,
    lastSeen: "12m ago",
    ip: "10.7.19.220",
  },
  {
    host: "ENG-MBP-047",
    os: "macOS 14.5",
    owner: "michael.johnson",
    risk: 12,
    status: "Healthy",
    isolated: false,
    lastSeen: "1h ago",
    ip: "10.19.4.11",
  },
  {
    host: "MKT-LT-118",
    os: "Windows 11 Pro 23H2",
    owner: "emily.davis",
    risk: 8,
    status: "Healthy",
    isolated: false,
    lastSeen: "3h ago",
    ip: "10.23.44.9",
  },
];

export const signedOverTime = [
  { m: "Jan", investigations: 120, target: 100 },
  { m: "Feb", investigations: 168, target: 140 },
  { m: "Mar", investigations: 205, target: 180 },
  { m: "Apr", investigations: 244, target: 220 },
  { m: "May", investigations: 281, target: 260 },
  { m: "Jun", investigations: 322, target: 300 },
  { m: "Jul", investigations: 361, target: 330 },
];

export const mitreCoverage = [
  { tactic: "Initial Access", cov: 78 },
  { tactic: "Execution", cov: 84 },
  { tactic: "Persistence", cov: 62 },
  { tactic: "Priv. Escalation", cov: 71 },
  { tactic: "Defense Evasion", cov: 68 },
  { tactic: "Credential Access", cov: 88 },
  { tactic: "Discovery", cov: 74 },
  { tactic: "Lateral Movement", cov: 66 },
  { tactic: "Collection", cov: 59 },
  { tactic: "Exfiltration", cov: 63 },
  { tactic: "Impact", cov: 72 },
];

export const leaderboard = [
  { name: "Elena Rossi", score: 9820, solved: 148 },
  { name: "Marcus Chen", score: 9414, solved: 141 },
  { name: "Priya Nair", score: 8977, solved: 133 },
  { name: "Yusuf Demir", score: 8541, solved: 129 },
  { name: "Amelia Ward", score: 8102, solved: 121 },
];

export const scenarios = [
  {
    id: "SC-081",
    title: "BEC via OAuth consent phishing",
    difficulty: "Advanced",
    duration: "45 min",
    category: "Identity",
    mitre: ["T1566", "T1528", "T1114"],
    completion: 62,
    level: "Tier 2+",
  },
  {
    id: "SC-080",
    title: "Ransomware precursor: Cobalt Strike beacon",
    difficulty: "Expert",
    duration: "90 min",
    category: "Endpoint",
    mitre: ["T1059.001", "T1055", "T1021.002"],
    completion: 34,
    level: "Tier 3",
  },
  {
    id: "SC-079",
    title: "Password spray → Conditional Access bypass",
    difficulty: "Intermediate",
    duration: "35 min",
    category: "Identity",
    mitre: ["T1110.003", "T1078.004"],
    completion: 71,
    level: "Tier 1+",
  },
  {
    id: "SC-078",
    title: "Data exfiltration via SharePoint Graph API",
    difficulty: "Advanced",
    duration: "60 min",
    category: "Cloud",
    mitre: ["T1530", "T1567"],
    completion: 48,
    level: "Tier 2+",
  },
  {
    id: "SC-077",
    title: "Insider — USB staging on executive laptop",
    difficulty: "Intermediate",
    duration: "40 min",
    category: "Insider",
    mitre: ["T1091", "T1052.001"],
    completion: 66,
    level: "Tier 1+",
  },
  {
    id: "SC-076",
    title: "Living-off-the-land: certutil download",
    difficulty: "Intermediate",
    duration: "30 min",
    category: "Endpoint",
    mitre: ["T1105", "T1140"],
    completion: 74,
    level: "Tier 1+",
  },
];
