/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppThreatIntelRouteImport } from './routes/app.threat-intel'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppEndpointsRouteImport } from './routes/app.endpoints'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppInvestigationsIndexRouteImport } from './routes/app.investigations.index'
import { Route as AppInvestigationsIdRouteImport } from './routes/app.investigations.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatIntelRoute = AppThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointsRoute = AppEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsIndexRoute = AppInvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsIdRoute = AppInvestigationsIdRouteImport.update({
  id: '/investigations/$id',
  path: '/investigations/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/email': typeof AppEmailRoute
  '/app/endpoints': typeof AppEndpointsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app/': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations/': typeof AppInvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/email': typeof AppEmailRoute
  '/app/endpoints': typeof AppEndpointsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations': typeof AppInvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/email': typeof AppEmailRoute
  '/app/endpoints': typeof AppEndpointsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/learning': typeof AppLearningRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app/': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations/': typeof AppInvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/certificates'
    | '/app/email'
    | '/app/endpoints'
    | '/app/identity'
    | '/app/incidents'
    | '/app/learning'
    | '/app/scenarios'
    | '/app/search'
    | '/app/threat-intel'
    | '/app/'
    | '/app/investigations/$id'
    | '/app/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/alerts'
    | '/app/certificates'
    | '/app/email'
    | '/app/endpoints'
    | '/app/identity'
    | '/app/incidents'
    | '/app/learning'
    | '/app/scenarios'
    | '/app/search'
    | '/app/threat-intel'
    | '/app'
    | '/app/investigations/$id'
    | '/app/investigations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/certificates'
    | '/app/email'
    | '/app/endpoints'
    | '/app/identity'
    | '/app/incidents'
    | '/app/learning'
    | '/app/scenarios'
    | '/app/search'
    | '/app/threat-intel'
    | '/app/'
    | '/app/investigations/$id'
    | '/app/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/threat-intel': {
      id: '/app/threat-intel'
      path: '/threat-intel'
      fullPath: '/app/threat-intel'
      preLoaderRoute: typeof AppThreatIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/endpoints': {
      id: '/app/endpoints'
      path: '/endpoints'
      fullPath: '/app/endpoints'
      preLoaderRoute: typeof AppEndpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations/': {
      id: '/app/investigations/'
      path: '/investigations'
      fullPath: '/app/investigations/'
      preLoaderRoute: typeof AppInvestigationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations/$id': {
      id: '/app/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/app/investigations/$id'
      preLoaderRoute: typeof AppInvestigationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppEmailRoute: typeof AppEmailRoute
  AppEndpointsRoute: typeof AppEndpointsRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppLearningRoute: typeof AppLearningRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSearchRoute: typeof AppSearchRoute
  AppThreatIntelRoute: typeof AppThreatIntelRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInvestigationsIdRoute: typeof AppInvestigationsIdRoute
  AppInvestigationsIndexRoute: typeof AppInvestigationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppEmailRoute: AppEmailRoute,
  AppEndpointsRoute: AppEndpointsRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppLearningRoute: AppLearningRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSearchRoute: AppSearchRoute,
  AppThreatIntelRoute: AppThreatIntelRoute,
  AppIndexRoute: AppIndexRoute,
  AppInvestigationsIdRoute: AppInvestigationsIdRoute,
  AppInvestigationsIndexRoute: AppInvestigationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
