/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppInvestigationsIndexRouteImport } from './routes/app.investigations.index'
import { Route as AppInvestigationsIdRouteImport } from './routes/app.investigations.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsIndexRoute = AppInvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsIdRoute = AppInvestigationsIdRouteImport.update({
  id: '/investigations/$id',
  path: '/investigations/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations/': typeof AppInvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations': typeof AppInvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/': typeof AppIndexRoute
  '/app/investigations/$id': typeof AppInvestigationsIdRoute
  '/app/investigations/': typeof AppInvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/identity'
    | '/app/incidents'
    | '/app/'
    | '/app/investigations/$id'
    | '/app/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/alerts'
    | '/app/identity'
    | '/app/incidents'
    | '/app'
    | '/app/investigations/$id'
    | '/app/investigations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/identity'
    | '/app/incidents'
    | '/app/'
    | '/app/investigations/$id'
    | '/app/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations/': {
      id: '/app/investigations/'
      path: '/investigations'
      fullPath: '/app/investigations/'
      preLoaderRoute: typeof AppInvestigationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations/$id': {
      id: '/app/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/app/investigations/$id'
      preLoaderRoute: typeof AppInvestigationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInvestigationsIdRoute: typeof AppInvestigationsIdRoute
  AppInvestigationsIndexRoute: typeof AppInvestigationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInvestigationsIdRoute: AppInvestigationsIdRoute,
  AppInvestigationsIndexRoute: AppInvestigationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
